[tool.poetry]
name = "wxc_sdk"
version = "1.15.0"
description = "SDK for Webex APIs with special focus on Webex Calling specific endpoints"
license = 'MIT'
authors = ["Johannes Krohn <jkrohn@cisco.com>"]
readme = 'README.rst'
homepage = 'https://github.com/jeokrohn/wxc_sdk'
documentation = 'https://wxc-sdk.readthedocs.io'

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.0"
requests = "^2.27.1"
requests-toolbelt = "^1.0.0"
pytz = "*"
aiohttp = "^3.8.1"
python-dateutil = "^2.8.2"
aenum = "^3.1.11"
PyYAML = "^6.0"
# TODO typing-extensions 4.6.0 breaks Literals in pydantic models
typing-extensions = "<4.6.0"

[tool.poetry.dev-dependencies]
Sphinx = "^4.4.0"
sphinx-rtd-theme = "^1.0.0"
flake8 = "^5.0.3"
pytest = "^7.1.1"
python-dotenv = "^1.0.0"
aiohttp = "^3.8.1"
PyJWT = "^2.4.0"
webexteamssdk = "^1.6.1"
beautifulsoup4 = "^4.11.1"
matplotlib = "^3.6.1"
selenium = "^4.5.0"
inflection = "^0.5.1"
test_helper = { git = "https://github.com/jeokrohn/test_helper.git" }
geopy = "^2.2.0"
backoff = "^2.2.1"
webexteamsbot = "^0.1.4"

[tool.poetry.group.dev.dependencies]
setuptools = "^67.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
